### ISSUE TITLE
json 구조가 유동적일 때 레트로핏 gson의 최적의 방법은 무엇일까요?

### ISSUE THREAD

**Issue by dure21** [galcyurio/my-planner#6]
상황에 따라 나타날 수도 있는 키값도 있고 없는 경우도 있는데 그냥 파싱을 시키면 오류가 날 것 같은데 어떻게 하는게 좋을 지 모르겠네요

**Comment by galcyurio** [comment]
gson 은 null object 를 지원합니다. 
https://stackoverflow.com/a/3923805/6686126

**Comment by dure21** [comment]
감사합니다 클래스에 다 넣어두고 null 처리만 잘해주면 될 듯합니다.
